name: Stuff

on:
  push:
    branches:
      - testing-workflows
  # pull_request:
  #   branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Version Github Release
        id: semantic_version
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          dry_run: true
          branches: |
            ['main','master','testing-workflows']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if released
        run: |
          if [ "${{ steps.semantic_version.outputs.new_release_published }}" != "true" ]; then
            echo "Not released"
            exit 1
          fi
      # - name: Convert release changelog markdown to Slack markdown
      #   id: slack_markdown
      #   uses: LoveToKnow/slackify-markdown-action@v1.0.0
      #   with:
      #     text: ${{ toJSON(steps.semantic_version.outputs.new_release_notes) }}
      - name: Build Slack notification
        run: |
          set -euo pipefail
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          PLATFORMS="${{ github.event.inputs.platforms }}"
          NEW_VERSION="${{ steps.semantic_version.outputs.new_release_version }}"
          HEADER="Releasing :rocket: v$NEW_VERSION"

          cat > og <<EOL
          ${{ steps.semantic_version.outputs.new_release_notes }}

          "and some double" and 'single' quotes here
          EOL
          cat og
          echo "------"

          CHANGELOG=$(cat og | jq --raw-input --slurp)
          echo ">>>$CHANGELOG<<<"

          cat > .slack_notification.json <<EOL
          {
            "text": "$HEADER",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "emoji": true,
                  "text": "$HEADER"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Environment(s): *${ENVIRONMENT}*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Platform(s): *${PLATFORMS}*"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": $CHANGELOG
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.GITHUB_RUN_URL }}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.ref_name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.sha }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "triggered by *${{ github.actor }}*"
                  }
                ]
              }
            ]
          }
          EOL
      - name: Check notification
        run: |
          set -euo pipefail

          cat .slack_notification.json | jq
