# This is a basic workflow to help you get started with Actions

name: Testing

on:
  push:
    branches: [ my-testing-branch ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Run a multi-line script
        run: |
          #!/bin/bash
          foo
          echo "bar"
