name: pull-request

on:
  pull_request:
    branches:
      - master

env:
  FLUTTER_PATH: '/opt/hostedtoolcache/flutter'
  FLUTTER_VERSION: '1.22.6'

jobs:
  # Gets all pubspec location paths and puts them into the matrix output
  # to be used by the next step in parallel
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.find-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - name: Find directories
        id: find-dirs
        run: |
          PUBSPEC_PATHS="$(find . -type f -name "pubspec.yaml" \
            | xargs -I ^ sh -c "echo ^" \
            | sed 's/pubspec.yaml//' \
            | jq -Rsc 'split("\n")[:-1]')"
          echo "$PUBSPEC_PATHS"
          echo "::set-output name=dir::$PUBSPEC_PATHS"
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_PATH }}
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

  # Validates a dir by analyzing & testing its contents
  validate:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.setup.outputs.dir) }}
      fail-fast: true
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_PATH }}
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}
      - run: echo "${{ matrix.dir }}"
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Install dependencies
        run: flutter packages get
      - name: Validate Format
        run: flutter format --dry-run --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze --no-pub
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
