name: pull-request-flutter-setup-test

on:
  pull_request:
    branches:
      - master

env:
  FLUTTER_VERSION: '3.7.6'

jobs:
  # Gets all pubspec location paths and puts them into the matrix output
  # to be used by the next step in parallel
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.find-dirs.outputs.dir }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      # TODO: cache pub dependencies (?)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: false